In [55]:
import numpy as np

In [14]:
sales = [0, 5, 155, 0, 518, 9, 1827, 616, 317, 325]
sales_array = np.array(sales)

In [15]:
sales_array

array([   0,    5,  155,    0,  518,    9, 1827,  616,  317,  325])

### array([ 0, 5, 155, 0, 518, 9, 1827, 616, 317, 325])
### ndim - dimensions (axes) in the array
### shape - the size of the array in each dimention
### size - the total numbe
### dtype - the data type

In [17]:
print(f" ndim: {sales_array.ndim}")

 ndim: 1


In [19]:
my_list = [x * 10 for x in range(1,11)]
my_list = np.array(my_list)

In [9]:
print(f"shape : {my_list.shape}")

ndin : (10,)


In [10]:
print(f"size : {my_list.size}")

size : 10


In [11]:
print(f"dtype : {my_list.dtype}")

dtype : int32


In [12]:
my_list.ndim

1

In [22]:
my_two_dim_array = my_list.reshape(2,5)
my_two_dim_array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [24]:
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
zeros = np.zeros((5,5), dtype=int)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
my_range = np.arange(10)
my_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_linspace = np.linspace(0, 100, 5)
my_linspace

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.arange(1, 9, 2).reshape(2, 2)

array([[1, 3],
       [5, 7]])

### np.default_rng(seed) -  
### default_rng.random(number)
### default_rng.normal(mean, stdev, number)


In [32]:
rng = np.random.default_rng(2222)
random_array = rng.random(10)
random_array

array([0.31795561, 0.27481238, 0.14987102, 0.45281912, 0.97248042,
       0.5906709 , 0.31928325, 0.46330719, 0.90628454, 0.64878647])

In [33]:
random_normal = rng.normal(5, 1, 10)
random_normal

array([4.36284252, 4.60450772, 3.83043857, 4.63452412, 4.13104347,
       5.74312454, 4.19740365, 2.89130483, 4.41776429, 5.95528344])

In [34]:
my_two_dim_array = my_list.reshape(5,2)
my_two_dim_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [37]:
my_a_array = np.arange(10, 101, 10).reshape(5,2)
my_a_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [38]:
my_lin_array = np.linspace(10, 100, 10).reshape(5,2)
my_lin_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [40]:
my_fun_array = (np.arange(1, 11) * 10).reshape(5,2)
my_fun_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [45]:
my_rng = np.random.default_rng(2022)
random_array = my_rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

### indexing & slicing one-dimensional arrays is the same as base python

In [46]:
integer_array = np.arange(12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
integer_array[2]

2

In [48]:
integer_array[-1]

11

In [49]:
integer_array[-2]

10

In [50]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [51]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

### array(row index, column index) - indexing to access a single element(0 - indexed)

In [57]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
new_array[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
new_array[:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [61]:
new_array[2,1]

9

In [75]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [77]:
random_array[:, 0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [78]:
random_array[2, 1]

0.04305584439252108

In [79]:
sales_array

array([   0,    5,  155,    0,  518,    9, 1827,  616,  317,  325])

In [80]:
sales_array + 2

array([   2,    7,  157,    2,  520,   11, 1829,  618,  319,  327])

In [82]:
quantity = new_array[0, :]
quantity

array([0, 1, 2, 3])

In [83]:
price = new_array[1, :]

In [84]:
price

array([4, 5, 6, 7])

In [85]:
quantity * price

array([ 0,  5, 12, 21])

In [91]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

In [87]:
prices

array([ 5.99,  6.99, 22.49, 99.99, 49.99])

In [92]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [90]:
discount_pct = random_array[:2].reshape(6)
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [93]:
pct_owed = 1 - discount_pct
pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [94]:
final_owed = total * pct_owed
final_owed.round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

### filtering arrays

In [97]:
sales_array[sales_array != 0]

array([   5,  155,  518,    9, 1827,  616,  317,  325])

In [98]:
sales_array[(sales_array == 616)]

array([616])

In [99]:
sales_array[(sales_array == 616) | (sales_array < 100)]

array([  0,   5,   0,   9, 616])

In [101]:
sales_array[(sales_array > 100) & (sales_array < 500)]

array([155, 317, 325])

In [102]:
mask = (sales_array > 100) & (sales_array < 500)
sales_array[mask]

array([155, 317, 325])

In [103]:
product_array = np.array(['fruits', 'vegtable', 'cereal', 'dairy', 'eggs'])
product_array

array(['fruits', 'vegtable', 'cereal', 'dairy', 'eggs'], dtype='<U8')

In [105]:
new_array = new_array[0, :]
new_array

array([0, 1, 2, 3])

### modifying array values

In [108]:
new_array

array([0, 1, 2, 3])

In [110]:
new_array[1] = 25
new_array

array([ 0, 25,  2,  3])

In [111]:
new_array[new_array == 0] = 5
new_array

array([ 5, 25,  2,  3])

### the where function
np.where(logical, value if true, value if false)


In [112]:
inventory_array = np.array([12, 102, 18, 0, 0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [113]:
np.where(inventory_array <= 0, 'Out of stock', 'In stock')

array(['In stock', 'In stock', 'In stock', 'Out of stock', 'Out of stock'],
      dtype='<U12')

In [115]:
np.where(inventory_array <= 0, "out of stock", product_array)

array(['fruits', 'vegtable', 'cereal', 'out of stock', 'out of stock'],
      dtype='<U12')

In [116]:
sales = [0, 5, 155, 0, 518, 9, 1827, 616, 317, 325]
sales_array = np.array(sales).reshape(2,5)
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [117]:
sales_array.sum()

3772

In [118]:
sales_array.mean()

377.2

In [119]:
sales_array.max()

1827

In [120]:
sales_array.min()

0

In [121]:
sales_array.sum(axis = 0)

array([   9, 1832,  771,  317,  843])

In [122]:
sales_array.sum(axis = 1)

array([ 678, 3094])

In [125]:
np.median(sales_array)

236.0

In [126]:
np.percentile(sales_array, 90)

737.0999999999996

In [127]:
np.unique(sales_array)

array([   0,    5,    9,  155,  317,  325,  518,  616, 1827])

In [128]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 3.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [129]:
sales_array.sort(axis = 1)
sales_array

array([[   0,    0,    5,  155,  518],
       [   9,  317,  325,  616, 1827]])

In [141]:
def for_loop_multiply_list(list1, list2):
    product_list = []
    for element1, element2 in zip(list1, list2):
        product_list.append(element1 * element2)
    return product_list

def multiply_array(array1, array2):
    return array1 * array2

In [136]:
list1 = list(range(1000))
list2 = list(range(1000))

In [139]:
%%timeit -r 5 -n 10000
for_loop_multiply_list(list1, list2)

74.2 µs ± 259 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [144]:

%%timeit -r 5 -n 10000
multiply_array(np.array(list1), np.array(list2))

90.3 µs ± 672 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)
